V1

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -1,24 +1,15 @@
-name: GitHub Actions Demo
-on: [push]
+name: Security PR handler
+
+on: 
+  pull_request:
+    types: [ push, labeled ]
+
 jobs:
-  Explore-GitHub-Actions:
+  Check-PR-Forbidden-Tags:
+    if: ${{ github.event.label.name == "DON'T MERGE" || github.event.label.name == "Don't squash" }}
     runs-on: ubuntu-latest
     steps:
-      - name: Check out repository code
-        uses: actions/checkout@v3
-      - name: Fetch tags
-        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
-      - name: Display all tags
-        run: |
-          echo "Bonjour"
-      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
-      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
-      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
-      - name: Check out repository code
-        uses: actions/checkout@v3
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
-      - name: List files in the repository
-        run: |
-          ls ${{ github.workspace }}
-      - run: echo "🍏 This job's status is ${{ job.status }}."
+      - name: Forbidden tags detected
+        run: echo "Don't merge / Don't squash tags detected. Failing to prevent merge"
+      - name: Create failure
+        run: exit 1
