Some refacto

diff --git a/.github/workflows/github-actions-demo.yml b/.github/workflows/github-actions-demo.yml
--- a/.github/workflows/github-actions-demo.yml
+++ b/.github/workflows/github-actions-demo.yml
@@ -8,10 +8,8 @@ jobs:
   Check-PR-Forbidden-Tags:
     runs-on: ubuntu-latest
     steps:
-      - name: Exit if no corresponding tags detected
-        if: github.event.label.name != 'DON%25T MERGE' && github.event.label.name != 'Don t squash'
-        run: exit 0
-      - name: Forbidden tags detected
-        run: echo "Don't merge / Don't squash tags detected. Failing to prevent merge"
-      - name: Create failure
-        run: exit 1
+      - name: Forbidden tags detection
+        if: github.event.label.name == 'DON T MERGE' || github.event.label.name == 'Don t squash'
+        run: | 
+          echo "Don't merge / Don't squash tags detected. Failing to prevent merge"
+          exit 1
